#language: python
os:
  - osx
# osx does not support python, install it manually
before_install:
  - which python
  - python --version
  - pip install virtualenv
  - which virtualenv
  - virtualenv venv
  - source venv/bin/activate
#  - brew update
#  - brew outdated pyenv || brew upgrade pyenv
#  - eval "$( pyenv init - )"
#  - pyenv install 2.7
#  - pyenv global 2.7
#  - pyenv versions
  - pip install --upgrade pip
  - which pip
  - pip --version
#  - mkdir /Users/travis/bin
#  - pip install -v --target=/Users/travis/bin --install-option="--prefix=/Users/travis/bin --target=/Users/travis/bin" --upgrade pip
  - printenv SHELL
  - printenv PATH
  - printenv HOME
  - printenv PWD
# install dependencies
install:
  - pip install numpy
#  - pip install --trusted-host www.simpleitk.org -f http://www.simpleitk.org/SimpleITK/resources/software.html SimpleITK
  - wget 'https://sourceforge.net/projects/simpleitk/files/SimpleITK/0.10.0/Python/SimpleITK-0.10.0-cp27-cp27m-macosx_10_6_intel.whl'
  - which python
  - python --version
  - pip install 'SimpleITK-0.10.0-cp27-cp27m-macosx_10_6_intel.whl'
  - pip install nose
  - pip install nose-parameterized
  - pip install tqdm
  - git clone https://github.com/nigma/pywt.git && cd pywt && python setup.py install && cd ..
  - python --version

# run tests
script:
  - which python
  - python --version
  - nosetests --nocapture --verbosity=3 tests/test_basic.py
  - nosetests --nocapture --verbosity=3 tests/test_sitk.py
